# The default build environment is Ubuntu 12.04 (very old!) which doesn't
# support c++11, which we need for our bindings.  Instead, use the newer trusty
# (14.04) distribution.
sudo: required
dist: trusty

language: go
go:
  - tip
install: ./install_v8_linux.sh
notifications:
  email:
    on_failure: change
