# The default build environment is Ubuntu 12.04 (very old!) which doesn't
# support c++11, which we need for our bindings.  Instead, use the newer trusty
# (14.04) distribution.
sudo: required
dist: trusty

env:
  - V8_VERSION=5.7.140.0
  - V8_VERSION=5.6.326.18
  - V8_VERSION=5.5.372.29
  - V8_VERSION=5.4.524
  - V8_VERSION=5.4.500.6
  - V8_VERSION=5.3.351
  - V8_VERSION=5.2.371
  - V8_VERSION=5.1.300
  - V8_VERSION=5.0.105
  - V8_VERSION=4.9.391
  - V8_VERSION=4.8.271.17

language: go
go:
  - tip
install: ./travis-install-linux.sh
notifications:
  email:
    on_failure: change
